config/routes.rb
Rails.application.routes.draw do
  root 'token_urls#new'
  get '/:token', to: 'token_urls#show', as: 'token_urls_redirects'
  get '/:token/info', to: 'token_urls#index', as: 'token_urls_index'
  # Improvement: Check if I can change resource base url to '/' instead of 'tiny_url' so I can just put everything in resource?
  resources :token_urls, only: [:create]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/internet_protocol.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: internet_protocols
#
#  id           :bigint           not null, primary key
#  token_url_id :bigint
#  address      :string           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class InternetProtocol < ApplicationRecord
  belongs_to :token_url

  validates_presence_of :address
end

app/models/token_url.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: token_urls
#
#  id         :bigint           not null, primary key
#  url        :string           not null
#  token      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class TokenUrl < ApplicationRecord
  has_many :internet_protocols, dependent: :destroy

  validates_presence_of :url
  validates_uniqueness_of :url, :token

  before_create :generate_token, unless: :token?

  def generate_token
    self.token = SecureRandom.hex(3)
    generate_token if TokenUrl.exists?(token)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/token_urls_controller.rb
# frozen_string_literal: true

class TokenUrlsController < ApplicationController
  before_action :set_token_url, only: %i[show index]

  def new
    @token_url = TokenUrl.new
  end

  def create
    @token_url = TokenUrl.find_or_create_by(token_url_params)
    render json: { new_url: token_url }
  rescue StandardError => e # TODO: better error 
    render json: { error: e }, status: 400
  end

  def show
    if @token_url
      @token_url.internet_protocols.create(address: request.remote_ip)
      redirect_to @token_url.url
    else
      redirect_to root_url, flash: { error: 'Token do not exist' }
    end
  end

  def index
    if @token_url
      @ip_addresses = @token_url.internet_protocols
    else
      redirect_to root_url, flash: { error: 'Token do not exist' }
    end
  end

  private

  def set_token_url
    @token_url = TokenUrl.find_by(token: params[:token])
  end

  def token_url_params
    params[:token_url].permit(
      :url
    )
  end

  def token_url
    Rails.application.routes.url_helpers.token_urls_redirects_url(token: @token_url.token) if @token_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/token_urls_helper.rb
module TokenUrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TinyUrl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div>
        <%= value %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/token_urls/index.html.slim
.d-flex.justify-content-center.align-items-center.h-100
  .all
    table.table
      thead
        tr
          th scope="col"  ID 
          th scope="col"  Address
          th scope="col"  Viewed At
      tbody
        - @ip_addresses.each do | ip_address |
          tr
            th scope="row"
              = ip_address.id
            td
              = ip_address.address
            td
              = ip_address.created_at
    = link_to root_url do
      button
        | "Create More TokenUrl"

app/views/token_urls/new.html.slim
.d-flex.justify-content-center.align-items-center.h-100
  .card
    .card-header
      | Create Token URL
    .card-body
      =form_with(model: @token_url, url: token_urls_path, id: "new_token_url", local: false) do |f| 
        .form-group
          label for="tokenUrlUrl" URL
          = f.url_field :url, class: "form-control mb-3", placeholder: ("Enter a long url"), id: "tokenUrlUrl", required: true
        = f.submit class: "btn btn-primary"
      #result
javascript:
  window.addEventListener("turbolinks:load", () => {
    const element = document.querySelector("#new_token_url");
    const result = document.querySelector("#result");

    function createLinkTo(link, div) {
      div.innerHTML = ''; // TODO: Fix this part
      var a = document.createElement('a');
      a.setAttribute('href',link);
      a.innerHTML = link;
      div.appendChild(a)
    }

    element.addEventListener("ajax:success", (event) => {
      const [_data, _status, xhr] = event.detail;
      createLinkTo(_data["new_url"], result);
    });
    element.addEventListener("ajax:error", (event) => {
      const [_data, _status, xhr] = event.detail;
      result.innerHTML = _data["error"]
    });
  });